name: MinecartAnnouncer
version: 2.0.0
main: com.warterpl.minecartannoucer.MinecartAnnouncer
api-version: 1.21.5
commands:
  dev_showRailMessages:
    description: Can display messages while traveling via minecart
    usage: showRailMessages