name: MinecartAnnouncer
version: 2.1.0
main: com.warterpl.minecartannoucer.MinecartAnnouncer
api-version: 1.21.5
commands:
  dev_showRailMessages:
    description: Can display messages while traveling via minecart
    usage: showRailMessages
    permission: minecartannouncer.dev
