name: MinecartAnnouncer
version: 1.2.3
main: com.warterpl.minecartannoucer.MinecartAnnouncer
api-version: 1.21.5
commands:
  showRailMessages:
    description: Can display messages while traveling via minecart
    usage: showRailMessages